### ISSUE TITLE
Demo 4 Checklist

### ISSUE THREAD

**Issue by iwandejong** [COS301-SE-2024/Crop-Prediction-System#264]
### SRS
@iwandejong @Xavier893 
- [ ] Update Requirements
- [ ] Ensure QR matches product outcomes
- [ ] Update Design Patterns
- [ ] Update Use Case Diagrams
- [ ] Update User Stories
- [ ] Update Constraints
- [ ] Add Backend Class Diagram
- [ ] Add Database Schema

### Architectural Diagram
@Xavier893 
- [ ] Review in general

### Coding Standards
@Tiaan2 
- [ ] Solidify coding standards
- [ ] Review coding standards across the entire codebase

### Technical Installation
- [ ] Add Database Schema @iwandejong 
- [ ] Add Supabase Functions @Tiaan2 

### User Manual
@Xavier893 
- [ ] Fully update
- [ ] Look at guideline on CS Web page

### ML Model Research
@iwandejong 
- [ ] Complete ML Model document

### Testing policy document
@SMangera8 @SW1F7YY 
- [ ] Make & complete testing policy document

### Frontend
- [ ] Code cleanup @Xavier893 @Tiaan2 
- [ ] Acknowledgement Page @Xavier893 
- [ ] Help Menu @Xavier893 

### Backend
- [ ] Code cleanup @iwandejong 

### Frontend
@SMangera8
- [ ] Unit (vitest)
- [ ] Integration
- [ ] E2E (cypress)

### Backend
- [ ] Unit (pytest) @SW1F7YY 
- [ ] Integration (Postman) @Tiaan2 

## Admin
- [ ] Make presentation @iwandejong 
- [ ] Record demo
- [ ] Burndown chart @iwandejong 
- [ ] Clean up issues & project board

## CI/CD
@Tiaan2 
- [ ] Cleanup workflows, make sure they work
- [ ] Delete unused workflows
- [ ] Delete unused branches

**Comment by Tiaan2** [comment]
Files to improve on regarding coding standards:

- frontend\pages\inputs\manage-fields\index.vue (@Xavier893)
- frontend\pages\market\index.vue (@Xavier893)
- frontend\components\FieldCard.vue (@Xavier893)
- frontend\components\LogsView.vue (@Tiaan2)
- landing-page\pages\index.vue (@Tiaan2)

**Comment by iwandejong** [comment]
![Uploading image.png…]()
@Tiaan2

**Comment by Xavier893** [comment]
@iwandejong the Architectural Requirements are on the docs branch, just review please
