### ISSUE TITLE
Project Day To-Do

### ISSUE THREAD

**Issue by iwandejong** [COS301-SE-2024/Crop-Prediction-System#299]
### @iwandejong 

- [x]  T-shirts collect
- [x]  Make posters
- [x]  Print posters
- [ ]  TV 32” — USB
- [x]  Pins
- [ ]  Clear up fields
- [ ]  Trekker
- [ ]  Mousepad

### @Tiaan2 

- [x]  Console.logs delete & redeploy
- [x]  CodeCov
- [ ]  Extension plug

### @SW1F7YY 

- [x]  Fix Backend
- [ ]  CV

### @SMangera8 

- [x]  Fix Frontend
- [ ]  Extension & Multiplug
- [ ]  CV

### @Xavier893 

- [x]  Clean up team chat
- [x]  Mulitplug
- [x]  24inch monitor
- [x]  HDMI cable
- [x]  Keyboard
- [x]  Mouse
